//
//  Constants.swift
//  DouYuZhiBo
//
//  Created by 买明 on 23/04/2017.
//  Copyright © 2017 买明. All rights reserved.
//

import UIKit

let STATUS_BAR_HEIGHT: CGFloat = 20.0
let NAVIGATION_BAR_HEIGHT: CGFloat = 44.0
let TAB_BAR_HEIGHT: CGFloat = 44.0

let SCREEN_WIDTH: CGFloat = UIScreen.main.bounds.width
let SCREEN_HEIGHT: CGFloat = UIScreen.main.bounds.height

// HomeViewController
let TITLE_VIEW_HEIGHT: CGFloat = 40.0

// PageTitleView
let PAGE_TITLE_VIEW_UNDERLINE_HEIGHT: CGFloat = 2.0
let PAGE_TITLE_LABEL_NORMAL_COLOR: (CGFloat, CGFloat, CGFloat) = (85, 85, 85)
let PAGE_TITLE_LABEL_HIGHLIGHTED_COLOR: (CGFloat, CGFloat, CGFloat) = (255, 128, 0)

// PageContentView
let PAGE_CONTENT_COLLECTION_VIEW_IDENTIFIER = "PAGE_CONTENT_COLLECTION_VIEW_IDENTIFIER"

// RecommandViewController
let RECOMMAND_CELL_MARGIN: CGFloat = 10.0
let RECOMMAND_CELL_WIDTH = (SCREEN_WIDTH - 3 * RECOMMAND_CELL_MARGIN) / 2
let RECOMMAND_CELL_HEIGHT = RECOMMAND_CELL_WIDTH * 4.0 / 3.0
let RECOMMAND_CELL_HEADER_HEIGHT: CGFloat = 50.0
let RECOMMAND_COLLECTION_VIEW_IDENTIFIER = "RECOMMAND_COLLECTION_VIEW_IDENTIFIER"
let RECOMMAND_HEADER_VIEW_IDENTIFIER = "RECOMMAND_HEADER_IDENTIFIER"
