//
//  Constants.swift
//  DouYuZhiBo
//
//  Created by 买明 on 23/04/2017.
//  Copyright © 2017 买明. All rights reserved.
//

import UIKit

let STATUS_BAR_HEIGHT: CGFloat = 20.0
let NAVIGATION_BAR_HEIGHT: CGFloat = 44.0
let TAB_BAR_HEIGHT: CGFloat = 44.0

let SCREEN_WIDTH: CGFloat = UIScreen.main.bounds.width
let SCREEN_HEIGHT: CGFloat = UIScreen.main.bounds.height

// HomeViewController
let TITLE_VIEW_HEIGHT: CGFloat = 40.0

// PageTitleView
let PAGE_TITLE_VIEW_UNDERLINE_HEIGHT: CGFloat = 2.0
let PAGE_TITLE_LABEL_NORMAL_COLOR: (CGFloat, CGFloat, CGFloat) = (85, 85, 85)
let PAGE_TITLE_LABEL_HIGHLIGHTED_COLOR: (CGFloat, CGFloat, CGFloat) = (255, 128, 0)

// PageContentView
let PAGE_CONTENT_COLLECTION_VIEW_IDENTIFIER = "PAGE_CONTENT_COLLECTION_VIEW_IDENTIFIER"

// RecommandViewController
let RECOMMAND_CELL_MARGIN: CGFloat = 10.0
let RECOMMAND_CELL_WIDTH = (SCREEN_WIDTH - 3 * RECOMMAND_CELL_MARGIN) / 2.0
let RECOMMAND_NORMAL_CELL_HEIGHT = RECOMMAND_CELL_WIDTH * 3.0 / 4.0
let RECOMMAND_YANZHI_CELL_HEIGHT = RECOMMAND_CELL_WIDTH * 4.0 / 3.0
let RECOMMAND_CELL_HEADER_HEIGHT: CGFloat = 50.0
let RECOMMAND_NORMAL_CELL_IDENTIFIER = "RECOMMAND_NORMAL_CELL_IDENTIFIER"
let RECOMMAND_YANZHI_CELL_IDENTIFIER = "RECOMMAND_YANZHI_CELL_IDENTIFIER"
let RECOMMAND_HEADER_VIEW_IDENTIFIER = "RECOMMAND_HEADER_IDENTIFIER"
let RECOMMAND_RECYCLE_VIEW_HEIGHT = SCREEN_WIDTH * 3.0 / 8.0
let RECOMMAND_RECYCLE_VIEW_IDENTIFIER = "RECOMMAND_RECYCLE_VIEW_IDENTIFIER"
let RECOMMAND_GAME_VIEW_HEIGHT: CGFloat = 90.0
let RECOMMAND_GAME_VIEW_IDENTIFIER = "RECOMMAND_GAME_VIEW_IDENTIFIER"

// RecommandGameView
let RECOMMAND_GAME_VIEW_INSET_LR: CGFloat = 15.0

// GameViewController
let GAME_COLLECTION_MARGIN: CGFloat = 10.0
let GAME_COLLECTION_ITEM_WIDTH = (SCREEN_WIDTH - 2.0 * GAME_COLLECTION_MARGIN) / 3.0
let GAME_COLLECTION_ITEM_HEIGHT = GAME_COLLECTION_ITEM_WIDTH * 6.0 / 5.0
let GAME_COLLECTION_IDENTIFIER = "GAME_CONTROLLER_COLLECTION_IDENTIFIER"
let GAME_COLLECTION_HEADER_HEIGHT: CGFloat = 50.0
let GAME_COLLECTION_HEADER_IDENTIFIER = "GAME_COLLECTION_HEADER_IDENTIFIER"
let GAME_GAME_VIEW_HEIGHT: CGFloat = 90.0

// EntertainmentView
let ENTERTAINMENT_MENU_VIEW_HEIGHT: CGFloat = 200.0

// EntertainmentMenuView
let ENTERTAINMENT_MENU_COLLECTION_CELL_IDENTIFIER = "ENTERTAINMENT_MENU_COLLECTION_CELL_IDENTIFIER"
let ENTERTAINMENT_MENU_INNER_CELL_IDENTIFIER = "ENTERTAINMENT_MENU_INNER_CELL_IDENTIFIER"

// FunViewController
let FUN_CONTROLLER_TOP_MARGIN: CGFloat = 10.0
